name: flutter_app
description: Where Every Achievement is a Summit Conquered.
publish_to: none
version: 2.4.3
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.3
  material: ^1.0.0+2
  path_provider: ^2.1.1
  webview_flutter_android: ^3.13.2
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/icon.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/icon.png
    icon_size: 96
  macos:
    generate: true
    image_path: assets/icon.png
