name: Build

on:
  push:
    branches:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - name: Install jq
      run: sudo apt-get install jq

    - name: Install dependencies
      run: |
        npm install -g webpack @types/jest jest typescript webpack-cli npm-run-all
        npm ci

    - name: Activate Syncfusion License
      run: npx syncfusion-license activate
      env:
        SYNCFUSION_LICENSE: ${{ secrets.SYNCFUSION_LICENSE }}
        
    - name: Build Summit
      run: |
        mkdir -p ./dist
        npx webpack --config webpack.config.js --mode production
      working-directory: ${{ github.workspace }}

    - name: Upload web extension as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Summit
        path: dist/*