name: Build and Release Chrome Extension

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Extract version
      id: get_version
      run: |
        cd browser-extension
        VERSION=$(jq -r .version manifest.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Print version
      run: echo "Version is ${{ env.VERSION }}"

    - name: Check if release already exists
      if: github.ref == 'refs/heads/main'
      id: check_release
      run: |
        RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ steps.get_version.outputs.VERSION }}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" || echo '{"message": "Not Found"}')
        MESSAGE=$(echo $RELEASE | jq -r .message)
        if [[ $MESSAGE == "Not Found" ]]; then
          echo "Release with version ${{ steps.get_version.outputs.VERSION }} does not exist."
        else
          echo "Release with version ${{ steps.get_version.outputs.VERSION }} already exists."
          exit 1
        fi

    - name: Create bin directory
      run: |
        mkdir -p ./browser-extension/bin
        mkdir -p ./terrain-context/bin
      working-directory: ${{ github.workspace }}

    - name: Install global dependencies
      run: npm install -g webpack @types/jest @vscode/vsce cordova jest typescript webpack-cli webpack

    - name: Install dependencies
      run: |
        cd browser-extension
        npm ci
        cd ../terrain-context
        npm ci
      
    - name: Remove and re-add Android platform
      run: |
        cd cordova-app
        cordova platform rm android
        cordova platform add android

    - name: Build Contents
      run: npx webpack --config webpack.prod.js
      working-directory: ${{ github.workspace }}/terrain-context

    - name: Build project
      run: npx webpack --config webpack.prod.js
      working-directory: ${{ github.workspace }}/browser-extension 
    
    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet

    - name: Set Cordova app version
      run: |
        cd cordova-app
        xmlstarlet ed --inplace -u "/widget/@version" -v "${{ steps.get_version.outputs.VERSION }}" config.xml

    - name: Build Cordova app
      run: |
        echo ${{ secrets.PLAY_UPLOAD_KEYSTORE }} | base64 --decode > upload-key.keystore
        cd cordova-app
        cordova prepare
        cordova build android --release

    - name: Sign APK
      run: |
        ${ANDROID_HOME}/build-tools/29.0.2/apksigner sign --ks upload-key.keystore --ks-key-alias ${{ secrets.PLAY_UPLOAD_ALIAS }} --ks-pass pass:${{ secrets.PLAY_UPLOAD_PASSWORD }} --key-pass pass:${{ secrets.PLAY_UPLOAD_PASSWORD }} cordova-app/platforms/android/app/build/outputs/bundle/release/app-release.aab

    - name: Zip summit
      run: |
        cd browser-extension
        zip -r summit.zip manifest.json bin/summit.js styles/* images/*

    - name: Upload web extension as artifact
      if: github.ref == 'refs/heads/dev'
      uses: actions/upload-artifact@v2
      with:
        name: web-extension
        path: ./browser-context/summit.zip

    - name: Upload AAB as artifact
      if: github.ref == 'refs/heads/dev'
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./cordova-app/platforms/android/app/build/outputs/bundle/release/app-release.aab

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/main'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./browser-context/summit.zip
        asset_name: summit.zip
        asset_content_type: application/zip
    
    - name: Upload AAB Release Asset
      if: github.ref == 'refs/heads/main'
      id: upload-aab-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cordova-app/platforms/android/app/build/outputs/bundle/release/app-release.aab
        asset_name: app-release.aab
        asset_content_type: application/vnd.android.package-archive

    # - name: Upload & release
    #   if: github.ref == 'refs/heads/main'
    #   uses: mnao305/chrome-extension-upload@v4.0.1
    #   with:
    #     file-path: ./summit.zip
    #     extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
    #     client-id: ${{ secrets.GOOGLE_ACCOUNT_CLIENT_ID }}
    #     client-secret: ${{ secrets.GOOGLE_ACCOUNT_CLIENT_SECRET }}
    #     refresh-token: ${{ secrets.GOOGLE_ACCOUNT_REFRESH_TOKEN }}
    #     publish: false
      
    # - uses: wdzeng/edge-addon@v1
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     product-id: ${{ secrets.EDGE_EXTENSION_ID }}
    #     zip-path: ./summit.zip
    #     client-id: ${{ secrets.EDGE_CLIENT_ID }}
    #     client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
    #     access-token-url: ${{ secrets.EDGE_REFRESH_TOKEN_URL }}