name: Chrome Extension Version Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get Version from PR branch
      id: get-pr-version
      run: |
        PR_VERSION=$(jq -r .version ./summit/package.json)
        echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV
        echo "The new version is ${{ env.PR_VERSION }}"


    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Get Version from Main branch
      id: get-main-version
      run: |
        MAIN_VERSION=$(jq -r .version ./summit/package.json)
        echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
        echo "The version in main is ${{ env.MAIN_VERSION }}"

    - name: Compare Versions
      run: |
        IFS='.' read -ra PR_VERSION <<< "${{ env.PR_VERSION }}"
        IFS='.' read -ra MAIN_VERSION <<< "${{ env.MAIN_VERSION }}"
        for i in "${!PR_VERSION[@]}"; do
          if (( PR_VERSION[i] > MAIN_VERSION[i] )); then
            echo "PR version is newer"
            exit 0
          elif (( PR_VERSION[i] < MAIN_VERSION[i] )); then
            echo "PR version is older"
            exit 1
          fi
        done
        echo "Versions are identical"
        exit 1